spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 20000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: 'ChangeMe!'
  lifetimeSeconds: 60000

server:
  context-path: ${contextpath:/api}
  compression:
    enabled: true
    mime-types: application/json

# Disable security locally so that the health end point shows full
# details and all Spring Boot Actuator end points are visible
management:
  security:
    enabled: false

alfresco:
  baseUrl: 'http://localhost:8088/alfresco/s/noms-spg'
  X-DocRepository-Remote-User: 'N00'
  X-DocRepository-Real-Remote-User: 'Smith,John'

logging.level.uk.gov: INFO