spring:
  application:
    name: community-api
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 20000
  profiles:
    include: stdout

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
  #        show_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

jwt:
  secret: 'ChangeMe!'
  lifetimeSeconds: 60000
  public:
    key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc09QQXRzUUFEZGJSdS9FSDZMUDUNCkJNMS9tRjQwVkRCbjEyaEpTWFBQZDVXWUswSExZMjBWTTdBeHhSOW1uWUNGNlNvMVd0N2ZHTnFVeC9XeWVtQnANCklKTnJzLzdEendnM3V3aVF1Tmg0ektSK0VHeFdiTHdpM3l3N2xYUFV6eFV5QzV4dDg4ZS83dk8rbHoxb0NuaXoNCmpoNG14TkFtczZaWUY3cWZuaEpFOVd2V1B3TExrb2prWnUxSmR1c0xhVm93TjdHVEdOcE1FOGR6ZUprYW0wZ3ANCjRveEhRR2hNTjg3SzZqcVgzY0V3TzZEdmhlbWc4d2hzOTZuelFsOG4yTEZ2QUsydXA5UHJyOUdpMkxGZ1R0N0sNCnFYQTA2a0M0S2d3MklSMWVGZ3pjQmxUT0V3bXpqcmU2NUhvTmFKQnI5dU5aelY1c0lMUE1jenpoUWovZk1oejMNCi9RSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=


server:
  servlet:
    context-path: ${contextpath:/}
  compression:
    enabled: true
    mime-types: application/json

# Disable security locally so that the health end point shows full
# details and all Spring Boot Actuator end points are visible
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

alfresco:
  baseUrl: 'http://localhost:8088/alfresco/s/noms-spg'
  X-DocRepository-Remote-User: 'N00'
  X-DocRepository-Real-Remote-User: 'Smith,John'

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG
  uris:
    exclude:
      regex: .*/health|*/info|*/ping|.*/swagger.*|/webjars/.*|

delius:
  ldap:
    users:
      base: "ou=Users,dc=moj,dc=com"
  baseurl: 'http://localhost:8999'
  username: 'default'
  password: 'default'

graceful:
  shutdown:
    enabled: false

azure:
  application-insights:
    web:
      enable-W3C: true

features:
   noms.update.custody: false