spring:
  application:
    name: community-api
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 20000
  profiles:
    include: stdout

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
  #        show_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

jwt:
  secret: 'ChangeMe!'
  lifetimeSeconds: 60000

server:
  servlet:
    context-path: ${contextpath:/api}
  compression:
    enabled: true
    mime-types: application/json

# Disable security locally so that the health end point shows full
# details and all Spring Boot Actuator end points are visible
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

alfresco:
  baseUrl: 'http://localhost:8088/alfresco/s/noms-spg'
  X-DocRepository-Remote-User: 'N00'
  X-DocRepository-Real-Remote-User: 'Smith,John'

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG
  uris:
    exclude:
      regex: .*/health|*/info|*/ping|.*/swagger.*|/webjars/.*|

delius:
  ldap:
    users:
      base: "cn=Users,dc=moj,dc=com"

graceful:
  shutdown:
    enabled: false

azure:
  application-insights:
    web:
      enable-W3C: true

