spring:
  datasource:
    url: 'jdbc:oracle:thin:@192.168.56.101:1521:DNDA'
    username: 'DELIUS_POOL'
    password: 'DELIUS_POOL_PASSWORD'
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: none
jwt:
  secret: 'ChangeMe!'

server:
  context-path: ${contextpath:/api}

flyway:
  enabled: false


