spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
  h2:
    console:
      enabled: true
  ldap:

    # Spring LDAP
    #
    # In this example we use an embedded ldap server. When using a real one,
    # you can configure the settings here.
    #
    # urls: ldap://localhost:12345
    # base: dc=memorynotfound,dc=com
    # username: uid=admin
    # password: secret

    # Embedded Spring LDAP
    embedded:
      base-dn: dc=memorynotfound,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:schema.ldif
      port: 12345
      validation:
        enabled: false
jwt:
  secret: 'ChangeMe!'
  lifetimeSeconds: 60000

server:
  context-path: ${contextpath:/api}

# Disable security locally so that the health end point shows full
# details and all Spring Boot Actuator end points are visible
management:
  security:
    enabled: false

alfresco:
  baseUrl: 'http://localhost:8088/alfresco/s/noms-spg'
  X-DocRepository-Remote-User: 'N00'
  X-DocRepository-Real-Remote-User: 'Smith,John'

logging.level.uk.gov: INFO