spring:
  datasource:
    url: 'jdbc:oracle:thin:@192.168.56.101:1521:DNDA'
    username: 'DELIUS_POOL'
    password: 'DELIUS_POOL_PASSWORD'
    hikari:
      maximum-pool-size: 50
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

server:
  shutdown: graceful

