spring:
  datasource:
    url: 'jdbc:oracle:thin:@192.168.56.101:1521:DNDA'
    username: 'DELIUS_POOL'
    password: 'DELIUS_POOL_PASSWORD'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

flyway:
  enabled: false


