spring:
  profiles:
    include: dev-seed

  jpa:
    properties:
      hibernate:
        show_sql: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub


logging.level.org.hibernate.SQL: DEBUG

features:
  apply-limited-access-markers: true