spring:
  application:
    name: community-api
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 20000
  profiles:
    include: stdout
    group:
      dev:
        - "dev-seed"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 10s

  codec:
    max-in-memory-size: 200MB

  data:
    web:
      pageable:
        max-page-size: 10000

jwt:
  secret: 'ChangeMe!'
  lifetimeSeconds: 60000

server:
  shutdown: immediate
  servlet:
    context-path: ${contextpath:/}
  compression:
    enabled: true
    mime-types: application/json

# Disable security locally so that the health end point shows full
# details and all Spring Boot Actuator end points are visible
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

alfresco:
  baseUrl: 'http://localhost:8088/alfresco/s/noms-spg'
  X-DocRepository-Remote-User: 'N00'
  X-DocRepository-Real-Remote-User: 'Smith,John'

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG
  uris:
    exclude:
      regex: .*/health|*/info|*/ping|.*/swagger.*|/webjars/.*|

delius:
  ldap:
    users:
      base: "ou=Users,dc=moj,dc=com"
  baseurl: 'http://localhost:8999'
  username: 'default'
  password: 'default'

deliusApi:
  baseurl: 'http://localhost:7999'

features:
  noms:
    update:
      custody: false
      booking.number: false
      keydates: false
      noms.number: false
      multiple-events:
        update-bulk-key-dates: false
        update-key-dates: false
        update-prison-location: false
  apply-limited-access-markers: false
  registers:
    court-code-allowed-pattern: ""

delius-integration-context:
  integration-contexts:
    commissioned-rehabilitation-services:
      provider-code: CRS
      staff-code: CRSUATU
      team-code: CRSUAT
      requirement-rehabilitation-activity-type: F
      nsi-mapping:
        nsi-status: INPROG
        contract-type-to-nsi-type:
          ACC: CRS01
      contact-mapping:
        appointment-rar-contact-type: CRSAPT
        appointment-non-rar-contact-type: CRS01
        enforcement-refer-to-offender-manager: ROM
        attendance-and-behaviour-notified-mapping-to-outcome-type:
          # Key values must be quoted otherwise they will get converted to true/false
          "yes":
            true: AFTC
            false: ATTC
          "late":
            true: AFTC
            false: ATTC
          "no":
            true: AFTA
            false: AFTA

smoke:
  test:
    aware: false

user-access:
  scopes:
    dont-apply-exclusions-for: "SCOPE_IGNORE_DELIUS_EXCLUSIONS_ALWAYS"
    dont-apply-restrictions-for: "SCOPE_IGNORE_DELIUS_INCLUSIONS_ALWAYS"

applicationinsights.connection.string: "InstrumentationKey=${APPINSIGHTS_INSTRUMENTATIONKEY}"
