spring:
  application:
    name: community-api
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 20000
      maximum-pool-size: 30
  profiles:
    include: stdout
    group:
      dev:
        - "dev-seed"

  mvc.pathmatch.matching-strategy: ant-path-matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 10s

  codec:
    max-in-memory-size: 200MB

  data:
    web:
      pageable:
        max-page-size: 10000

  ldap:
    base-environment:
      java.naming.ldap.derefAliases: never

jwt:
  secret: '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012' # must be at least 512 chars
  lifetimeSeconds: 60000

server:
  shutdown: immediate
  servlet:
    context-path: ${contextpath:/}
  compression:
    enabled: true
    mime-types: application/json

# Disable security locally so that the health end point shows full
# details and all Spring Boot Actuator end points are visible
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

alfresco:
  baseUrl: 'http://localhost:8088/alfresco/s/noms-spg'
  X-DocRepository-Remote-User: 'N00'
  X-DocRepository-Real-Remote-User: 'Smith,John'

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG
  uris:
    exclude:
      regex: .*/health|*/info|*/ping|.*/swagger.*|/webjars/.*|

delius:
  ldap:
    users:
      base: "ou=Users,dc=moj,dc=com"




features:
  noms:
    update:
      custody: false
      release: false
      booking.number: false
      keydates: false
      noms.number: false
      multiple-events:
        update-bulk-key-dates: false
        update-key-dates: false
        update-prison-location: false
  registers:
    court-code-allowed-pattern: ""

delius-integration-context:
  integration-contexts:
    commissioned-rehabilitation-services:
      provider-code: CRS
      staff-code: CRSUATU
      team-code: CRSUAT
      requirement-rehabilitation-activity-type: F
      nsi-mapping:
        nsi-status: INPROG
        nsi-end-status: COMP
        contract-type-to-nsi-type:
          ACC: CRS01
          ETE: CRS02
          PWB: CRS05
          WOS: CRS06
          DNR: CRS04
          MTR: CRS03
          WSM: CRS07
          FBD-EM: CRS08
          FBD-WM: CRS08
          FBD-L: CRS08
          FBD-SC: CRS08
          FBD-NE: CRS08
          FBD-W: CRS08
          FBD-Y: CRS08
          FBD-NW: CRS08
          DNR-K: CRS04
          DNR-L: CRS04
          DNR-NE: CRS04
          DNR-Y: CRS04
          DNR-NEN: CRS04
          DNR-SC: CRS04
          DNR-SY: CRS04
          DNR-WM: CRS04
          DNR-SW: CRS04
      contact-mapping:
        notification-contact-type: CRSNOTE
        appointment-rar-contact-type: CRSAPT
        appointment-non-rar-contact-type: CRSSAA
        enforcement-refer-to-offender-manager: ROM
        end-type-to-outcome-type:
          CANCELLED: CRS01
          PREMATURELY_ENDED: CRS02
          COMPLETED: CRS03
        initiated-by-service-provider-to-outcome-type:
          true: RSSR
          false: RSOF
        attendance-and-behaviour-notified-mapping-to-outcome-type:
          # Key values must be quoted otherwise they will get converted to true/false
          "yes":
            true: AFTC
            false: ATTC
          "late":
            true: AFTC
            false: ATTC
          "no":
            true: AFTA
            false: AFTA
    prison-to-probation:
      release-type-mapping:
        RELEASED: ADL # Adult Licence
        #TEMPORARY_ABSENCE_RELEASE: ROTL # Release on Temporary Licence. Note: this is not yet supported by Delius API
        #RELEASED_TO_HOSPITAL: TBC # Note: this is not yet supported by Delius API, and the Delius reference data has not been created yet
      recall-reason-mapping:
        ADMISSION: NN # Notified by Custodial Establishment
        #TEMPORARY_ABSENCE_RETURN: EOTL # End of Temporary Licence. Note: this is not yet supported by Delius API

smoke:
  test:
    aware: false

user-access:
  scopes:
    dont-apply-exclusions-for: "SCOPE_IGNORE_DELIUS_EXCLUSIONS_ALWAYS"
    dont-apply-restrictions-for: "SCOPE_IGNORE_DELIUS_INCLUSIONS_ALWAYS"

applicationinsights.connection.string: "InstrumentationKey=${APPINSIGHTS_INSTRUMENTATIONKEY}"

springdoc.swagger-ui:
  doc-expansion: none
  operations-sorter: alpha
  tags-sorter: alpha

sentry.traces-sample-rate: '0.05'
