version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.6
  aws-cli: circleci/aws-cli@1.4.0
  aws-ecs: circleci/aws-ecs@2.0.0
  mem: circleci/rememborb@0.0.1
  queue: eddiewebb/queue@1.5.0

jobs:
  validate-unit:
    executor:
      name: hmpps/java
      tag: "16.0"
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check --exclude-task testIntegration
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
  validate-integration:
    executor:
      name: hmpps/java
      tag: "16.0"
    parallelism: 4
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run:
          command: |
            circleci tests glob "src/testIntegration/**/*.java" | circleci tests split | xargs -n 1 echo
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" testIntegration -PtestFilter="`circleci tests glob "src/testIntegration/**/*.java" | circleci tests split`"
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
  deploy:
    parameters:
      env-vars:
        type: string
    docker:
      - image: circleci/python
    steps:
      - mem/recall:
          env_var: APP_VERSION
      - queue/until_front_of_line:
          consider-branch: false
          time: '10'
      - aws-cli/setup
      - run:
          name: Assume IAM role
          # This is a workaround for the aws-ecs/update-service CircleCI command not taking a profile parameter, and the underlying aws cli command not honouring the AWS_PROFILE env var.
          # See https://github.com/CircleCI-Public/aws-ecs-orb/issues/41 for further details
          command: |
            temp_role=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name "circleci-$CIRCLE_BUILD_NUM-$RANDOM")
            echo "export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)" >> $BASH_ENV; source $BASH_ENV;
            echo "export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)" >> $BASH_ENV; source $BASH_ENV;
            echo "export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)" >> $BASH_ENV; source $BASH_ENV;
            aws configure set aws_session_token "$(echo $temp_role | jq .Credentials.SessionToken | xargs)" --profile default
      - aws-ecs/update-service:
          cluster-name: $AWS_ECS_CLUSTER_NAME
          family: $AWS_ECS_ENV_NAME-community-api-task-definition
          service-name: $AWS_ECS_ENV_NAME-community-api-service
          container-image-name-updates: container=community-api,tag=$APP_VERSION
          container-env-var-updates: << parameters.env-vars >>
          verify-revision-is-deployed: true

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate-unit:
          filters:
            tags:
              ignore: /.*/
      - validate-integration:
          filters:
            tags:
              ignore: /.*/
      - hmpps/build_docker:
          name: build_docker
      - deploy:
          name: deploy_to_dev
          context: hmpps-delius-deploy-to-ecs-dev
          env-vars: >-
            container=community-api,name=SPRING_PROFILES_ACTIVE,                                value=oracle,
            container=community-api,name=SPRING_DATASOURCE_USERNAME,                            value=delius_pool,
            container=community-api,name=DELIUSAPI_BASEURL,                                     value=http://delius-api.ecs.cluster:8080/,
            container=community-api,name=DEBUG,                                                 value=true,
            container=community-api,name=SMOKE_TEST_AWARE,                                      value=true,
            container=community-api,name=SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI, value=https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json,
            container=community-api,name=APPLICATIONINSIGHTS_CONFIGURATION_FILE,                value=applicationinsights.dev.json
          requires:
            - build_docker
      - deploy:
          name: deploy_to_test
          context: hmpps-delius-deploy-to-ecs-test
          env-vars: >-
            container=community-api,name=SPRING_PROFILES_ACTIVE,                                      value=oracle,
            container=community-api,name=SPRING_DATASOURCE_USERNAME,                                  value=delius_pool,
            container=community-api,name=DELIUSAPI_BASEURL,                                           value=http://delius-api.ecs.cluster:8080/,
            container=community-api,name=SMOKE_TEST_AWARE,                                            value=true,
            container=community-api,name=SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI,       value=https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json,
            container=community-api,name=FEATURES_NOMS_UPDATE_CUSTODY,                                value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_BOOKING_NUMBER,                         value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_KEYDATES,                               value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_NOMS_NUMBER,                            value=true,
            container=community-api,name=FEATURES_APPLY_LIMITED_ACCESS_MARKERS,                       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_BULK_KEY_DATES,  value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_KEY_DATES,       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_PRISON_LOCATION, value=true,
            container=community-api,name=FEATURES_REGISTERS_COURT_CODE_ALLOWED_PATTERN,               value=XXXX[A-Z]{2},
            container=community-api,name=APPLICATIONINSIGHTS_CONFIGURATION_FILE,                      value=applicationinsights.dev.json
          requires:
            - deploy_to_dev
          filters:
            branches:
              only: main
      - request-pre-prod-approval:
          type: approval
          requires:
            - deploy_to_test
      - deploy:
          name: deploy_to_stage
          context: hmpps-delius-deploy-to-ecs-stage
          env-vars: >-
            container=community-api,name=SPRING_PROFILES_ACTIVE,                                      value=oracle,
            container=community-api,name=SPRING_DATASOURCE_USERNAME,                                  value=delius_pool,
            container=community-api,name=DELIUSAPI_BASEURL,                                           value=http://delius-api.ecs.cluster:8080/,
            container=community-api,name=SMOKE_TEST_AWARE,                                            value=true,
            container=community-api,name=SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI,       value=https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json,
            container=community-api,name=FEATURES_NOMS_UPDATE_CUSTODY,                                value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_BOOKING_NUMBER,                         value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_KEYDATES,                               value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_NOMS_NUMBER,                            value=true,
            container=community-api,name=FEATURES_APPLY_LIMITED_ACCESS_MARKERS,                       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_BULK_KEY_DATES,  value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_KEY_DATES,       value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_PRISON_LOCATION, value=false,
            container=community-api,name=FEATURES_REGISTERS_COURT_CODE_ALLOWED_PATTERN,               value=,
            container=community-api,name=APPLICATIONINSIGHTS_CONFIGURATION_FILE,                      value=applicationinsights.dev.json
          requires:
            - request-pre-prod-approval
      - deploy:
          name: deploy_to_perf
          context: hmpps-delius-deploy-to-ecs-perf
          env-vars: >-
            container=community-api,name=SPRING_PROFILES_ACTIVE,                                      value=oracle,
            container=community-api,name=SPRING_DATASOURCE_USERNAME,                                  value=delius_pool,
            container=community-api,name=DELIUSAPI_BASEURL,                                           value=http://delius-api.ecs.cluster:8080/,
            container=community-api,name=SMOKE_TEST_AWARE,                                            value=true,
            container=community-api,name=SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI,       value=https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json,
            container=community-api,name=FEATURES_NOMS_UPDATE_CUSTODY,                                value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_BOOKING_NUMBER,                         value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_KEYDATES,                               value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_NOMS_NUMBER,                            value=true,
            container=community-api,name=FEATURES_APPLY_LIMITED_ACCESS_MARKERS,                       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_BULK_KEY_DATES,  value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_KEY_DATES,       value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_PRISON_LOCATION, value=false,
            container=community-api,name=FEATURES_REGISTERS_COURT_CODE_ALLOWED_PATTERN,               value=,
            container=community-api,name=APPLICATIONINSIGHTS_CONFIGURATION_FILE,                      value=applicationinsights.dev.json
          requires:
            - request-pre-prod-approval
      - deploy:
          name: deploy_to_pre_prod
          context: hmpps-delius-deploy-to-ecs-pre-prod
          env-vars: >-
            container=community-api,name=SPRING_PROFILES_ACTIVE,                                      value=oracle,
            container=community-api,name=SPRING_DATASOURCE_USERNAME,                                  value=delius_pool,
            container=community-api,name=DELIUSAPI_BASEURL,                                           value=http://delius-api.ecs.cluster:8080/,
            container=community-api,name=SMOKE_TEST_AWARE,                                            value=false,
            container=community-api,name=SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI,       value=https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json,
            container=community-api,name=FEATURES_NOMS_UPDATE_CUSTODY,                                value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_BOOKING_NUMBER,                         value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_KEYDATES,                               value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_NOMS_NUMBER,                            value=true,
            container=community-api,name=FEATURES_APPLY_LIMITED_ACCESS_MARKERS,                       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_BULK_KEY_DATES,  value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_KEY_DATES,       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_PRISON_LOCATION, value=true,
            container=community-api,name=FEATURES_REGISTERS_COURT_CODE_ALLOWED_PATTERN,               value=,
            container=community-api,name=APPLICATIONINSIGHTS_CONFIGURATION_FILE,                      value=applicationinsights.json
          requires:
            - request-pre-prod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_to_stage
            - deploy_to_pre_prod
      - deploy:
          name: deploy_to_production
          context: hmpps-delius-deploy-to-ecs-prod
          env-vars: >-
            container=community-api,name=SPRING_PROFILES_ACTIVE,                                      value=oracle,
            container=community-api,name=SPRING_DATASOURCE_USERNAME,                                  value=delius_pool,
            container=community-api,name=DELIUSAPI_BASEURL,                                           value=http://delius-api.ecs.cluster:8080/,
            container=community-api,name=SMOKE_TEST_AWARE,                                            value=false,
            container=community-api,name=SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI,       value=https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json,
            container=community-api,name=FEATURES_NOMS_UPDATE_CUSTODY,                                value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_BOOKING_NUMBER,                         value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_KEYDATES,                               value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_NOMS_NUMBER,                            value=true,
            container=community-api,name=FEATURES_APPLY_LIMITED_ACCESS_MARKERS,                       value=true,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_BULK_KEY_DATES,  value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_KEY_DATES,       value=false,
            container=community-api,name=FEATURES_NOMS_UPDATE_MULTIPLE_EVENTS_UPDATE_PRISON_LOCATION, value=false,
            container=community-api,name=FEATURES_REGISTERS_COURT_CODE_ALLOWED_PATTERN,               value=,
            container=community-api,name=APPLICATIONINSIGHTS_CONFIGURATION_FILE,                      value=applicationinsights.json
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials

