defaults: &defaults
  working_directory: ~/app
  environment:
    JAVA_TOOL_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2

version: 2.1

orbs:
  owasp: entur/owasp@0.0.6
  hmpps: ministryofjustice/hmpps@1.0.0

executors:
  builder:
    <<: *defaults
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/app
  deployer:
    docker:
      - image: circleci/python:3
    working_directory: ~/app


jobs:
  build:
    executor: builder
    steps:
      - checkout
      - hmpps/create_app_version
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle
  build_docker:
    executor: deployer
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          docker_layer_caching: true
      - mem/recall:
          env_var: APP_VERSION
      - run:
          name: Build container and publish to docker hub
          command: |
            docker build -f docker/Dockerfile.aws --rm=false . \
               --tag "mojdigitalstudio/community-api:$APP_VERSION" \
               --label "maintainer=info@digital.justice.gov.uk" \
               --label "app.version=$APP_VERSION" \
               --label "build.version=$APP_VERSION" \
               --label "build.number=$CIRCLE_BUILD_NUM" \
               --label "build.url=$CIRCLE_BUILD_URL" \
               --label "build.gitref=$CIRCLE_SHA1"

            # publish to docker hub as the tag
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag mojdigitalstudio/community-api:$APP_VERSION mojdigitalstudio/community-api:latest
            docker push mojdigitalstudio/community-api:$APP_VERSION
            docker push mojdigitalstudio/community-api:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: builder

