FROM mojdigitalstudio/hmpps-base-java:latest
# Build time variables
ARG OFFENDERAPI_VERSION
ENV OFFENDERAPI_VERSION=$OFFENDERAPI_VERSION

USER root
RUN apk add curl jq

USER tools
COPY build/libs/delius-offender-api-*.jar /home/tools/delius-offender-api.jar
COPY build/libs/applicationinsights-agent*.jar /home/tools/agent.jar
COPY AI-Agent.xml /home/tools/

EXPOSE 8080

ENTRYPOINT ["/usr/bin/java", "-javaagent:/home/tools/agent.jar", "-jar", "/home/tools/delius-offender-api.jar"]
