ALTER TABLE OFFENDER DROP (
   PREV_CON_LAST_UPDATED_USER_ID,
   PREV_CON_LAST_UPD_AUTH_PROV_ID,
   PREV_CON_CREATED_PROVIDER_ID,
   PREV_CON_CREATED_BY_USER_ID,
   PREV_CON_CREATED_DATETIME,
   PREV_CON_ALFRESCO_DOCUMENT_ID,
   PREVIOUS_CONVICTION_DATE,
   PREVIOUS_CONVICTION_DOCUMENT,
   PREV_CONVICTION_DOCUMENT_NAME);

ALTER TABLE EVENT DROP (
   CPS_DATE,
   CPS_DOCUMENT,
   CPS_DOCUMENT_NAME,
   CPS_LAST_UPDATED_USER_ID ,
   CPS_LAST_UPDATED_AUTH_PROV_ID,
   CPS_CREATED_PROVIDER_ID,
   CPS_CREATED_BY_USER_ID,
   CPS_CREATED_DATETIME,
   CPS_ALFRESCO_DOCUMENT_ID,
   CPS_SOFT_DELETED);

ALTER TABLE DOCUMENT DROP COLUMN DOCUMENT;
