alter table DISABILITY
    add DISABILITY_CONDITION_ID  NUMBER references R_STANDARD_REFERENCE_LIST
;

alter table PROVISION
    add PROVISION_CATEGORY_ID  NUMBER references R_STANDARD_REFERENCE_LIST
;
