---
generic-service:
  replicaCount: 2
  ingress:
    host: community-api-test.hmpps.service.justice.gov.uk

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    ALFRESCO_BASEURL: https://hmpps-delius-alfresco-test.apps.live.cloud-platform.service.justice.gov.uk/alfresco/s/noms-spg
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENVIRONMENT: test

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
  businessHoursOnly: true