CREATE TABLE DISPOSAL
(
	DISPOSAL_ID NUMBER NOT NULL PRIMARY KEY,
	EVENT_ID NUMBER NOT NULL,
	SOFT_DELETED NUMBER NOT NULL,
	OFFENDER_ID NUMBER NOT NULL
);

CREATE TABLE CUSTODY
(
	CUSTODY_ID NUMBER NOT NULL PRIMARY KEY,
	DISPOSAL_ID NUMBER NOT NULL,
	SOFT_DELETED NUMBER NOT NULL,
	OFFENDER_ID NUMBER NOT NULL
);

CREATE TABLE INSTITUTIONAL_REPORT
(
	INSTITUTIONAL_REPORT_ID NUMBER NOT NULL	PRIMARY KEY,
	CUSTODY_ID NUMBER NOT NULL,
	SOFT_DELETED NUMBER NOT NULL,
	OFFENDER_ID NUMBER NOT NULL
);