CREATE TABLE R_CIRCUMSTANCE_SUB_TYPE
(
	CIRCUMSTANCE_SUB_TYPE_ID NUMBER NOT NULL PRIMARY KEY,
	CODE_VALUE VARCHAR2(100) NOT NULL,
	CODE_DESCRIPTION VARCHAR2(500) NOT NULL,
	SELECTABLE CHAR NOT NULL,
	ACTIVE_DUPLICATES CHAR NOT NULL,
	ROW_VERSION NUMBER DEFAULT 0 NOT NULL,
	CREATED_BY_USER_ID NUMBER NOT NULL,
	CREATED_DATETIME DATE NOT NULL,
	LAST_UPDATED_USER_ID NUMBER NOT NULL,
	LAST_UPDATED_DATETIME DATE NOT NULL,
	TRAINING_SESSION_ID NUMBER,
	QUALIFICATION_1_ID NUMBER(38, 0),
	QUALIFICATION_2_ID NUMBER(38, 0),
	QUALIFICATION_3_ID NUMBER(38, 0)
);


CREATE TABLE R_CIRCUMSTANCE_TYPE
(
	CIRCUMSTANCE_TYPE_ID NUMBER NOT NULL PRIMARY KEY,
	CODE_VALUE VARCHAR2(100) NOT NULL,
	CODE_DESCRIPTION VARCHAR2(500) NOT NULL,
	SELECTABLE CHAR NOT NULL,
	ACTIVE_DUPLICATES CHAR NOT NULL,
	ROW_VERSION NUMBER DEFAULT 0 NOT NULL,
	CREATED_BY_USER_ID NUMBER NOT NULL,
	CREATED_DATETIME DATE NOT NULL,
	LAST_UPDATED_USER_ID NUMBER NOT NULL,
	LAST_UPDATED_DATETIME DATE NOT NULL,
	TRAINING_SESSION_ID NUMBER,
	ENQUIRY NUMBER(22, 0),
	SPG_INTEREST NUMBER
);


CREATE TABLE PERSONAL_CIRCUMSTANCE
(
	PERSONAL_CIRCUMSTANCE_ID NUMBER NOT NULL PRIMARY KEY,
	 OFFENDER_ID NUMBER NOT NULL REFERENCES OFFENDER,
	 START_DATE DATE NOT NULL,
	 END_DATE DATE,
	 SOFT_DELETED NUMBER NOT NULL,
	 ROW_VERSION NUMBER DEFAULT 0 NOT NULL,
	 PARTITION_AREA_ID NUMBER NOT NULL,
	 CREATED_BY_USER_ID NUMBER NOT NULL,
	 LAST_UPDATED_USER_ID NUMBER NOT NULL,
	 TRAINING_SESSION_ID NUMBER,
	 CREATED_DATETIME DATE NOT NULL,
	 LAST_UPDATED_DATETIME DATE NOT NULL,
	 CIRCUMSTANCE_TYPE_ID NUMBER NOT NULL REFERENCES R_CIRCUMSTANCE_TYPE,
	 CIRCUMSTANCE_SUB_TYPE_ID NUMBER NOT NULL REFERENCES R_CIRCUMSTANCE_SUB_TYPE,
	 NOTES CLOB,
	 EVIDENCED CHAR,
	 QUALIFICATION_1_ID NUMBER(38, 0),
	 QUALIFICATION_2_ID NUMBER(38, 0),
	 QUALIFICATION_3_ID NUMBER(38, 0),
	 OFFENDER_ADDRESS_ID NUMBER DEFAULT NULL REFERENCES OFFENDER_ADDRESS,
	 PROBATION_AREA_ID NUMBER
);

create table TRAINING_SESSION
(
	TRAINING_SESSION_ID NUMBER not null
		constraint XPKTRAINING_SESSION
		primary key,
	NAME VARCHAR2(50) not null,
	SESSION_PASSWORD VARCHAR2(50) not null,
	constraint XAK1TRAINING_SESSION
	unique (NAME, TRAINING_SESSION_ID)
);

create table R_INSTITUTION
(
	INSTITUTION_ID NUMBER not null,
	ESTABLISHMENT CHAR not null
		constraint YES_OR_NO_ONLY30
		check (ESTABLISHMENT IN ('Y','N')),
	CODE CHAR(6) not null,
	DESCRIPTION VARCHAR2(100) not null,
	SELECTABLE CHAR not null
		constraint YES_OR_NO10
		check (SELECTABLE IN ('N','Y')),
	INSTITUTION_NAME VARCHAR2(100),
	FAX_NUMBER VARCHAR2(35),
	ADDRESS_ID NUMBER
		references ADDRESS,
	ROW_VERSION NUMBER default 0 not null,
	CREATED_DATETIME DATE not null,
	CREATED_BY_USER_ID NUMBER not null,
	LAST_UPDATED_DATETIME DATE not null,
	LAST_UPDATED_USER_ID NUMBER not null,
	TRAINING_SESSION_ID NUMBER
		references TRAINING_SESSION,
	ESTABLISHMENT_TYPE_ID NUMBER
		references R_STANDARD_REFERENCE_LIST,
	IMMIGRATION_REMOVAL_CENTRE CHAR
		constraint YES_OR_NO_ONLY_567802777
		check (IMMIGRATION_REMOVAL_CENTRE IN ('Y','N')),
	NOMIS_CDE_CODE VARCHAR2(50),
	PRIVATE NUMBER
		constraint TRUE_OR_FALSE_2088138974
		check (PRIVATE IN (0, 1)),
	constraint XPKR_INSTITUTION
	primary key (INSTITUTION_ID, ESTABLISHMENT),
	constraint XAK1R_INSTITUTION
	unique (CODE, TRAINING_SESSION_ID, INSTITUTION_ID, ESTABLISHMENT)
);


create table ALIAS
(
	ALIAS_ID NUMBER not null
		constraint XPKALIAS
		primary key,
	OFFENDER_ID NUMBER not null
		references OFFENDER,
	PARTITION_AREA_ID NUMBER not null
		references PARTITION_AREA,
	SECOND_NAME VARCHAR2(35),
	FIRST_NAME VARCHAR2(35) not null,
	THIRD_NAME VARCHAR2(35),
	SURNAME VARCHAR2(35) not null,
	DATE_OF_BIRTH_DATE DATE not null,
	FIRST_NAME_SOUNDEX VARCHAR2(50) not null,
	SOFT_DELETED NUMBER not null
		constraint TRUE_OR_FALSE67
		check (SOFT_DELETED IN (0, 1)),
	MIDDLE_NAME_SOUNDEX VARCHAR2(50),
	ROW_VERSION NUMBER default 0 not null,
	GENDER_ID NUMBER not null
		references R_STANDARD_REFERENCE_LIST,
	SURNAME_SOUNDEX VARCHAR2(50) not null,
	TRAINING_SESSION_ID NUMBER
		references TRAINING_SESSION,
	ORGANISATIONS T_ARR_ORGANISATIONS,
	CREATED_BY_USER_ID NUMBER not null,
	LAST_UPDATED_USER_ID NUMBER not null,
	CREATED_DATETIME DATE not null,
	LAST_UPDATED_DATETIME DATE not null
);
