INSERT INTO R_OFFENCE (OFFENCE_ID, CODE, DESCRIPTION, MAIN_CATEGORY_CODE, SELECTABLE, MAIN_CATEGORY_DESCRIPTION, ROW_VERSION, MAIN_CATEGORY_ABBREVIATION, OGRS_OFFENCE_CATEGORY_ID, SUB_CATEGORY_CODE, SUB_CATEGORY_DESCRIPTION, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME)
VALUES (1, '00101', 'Vehicle theft - 00101', '001', 'Y', 'Vehicle theft', 1, 'Vehicle theft', 1, '01', 'Vehicle theft', 1, '2017-01-01', 1, '2017-01-01');

INSERT INTO R_OFFENCE (OFFENCE_ID, CODE, DESCRIPTION, MAIN_CATEGORY_CODE, SELECTABLE, MAIN_CATEGORY_DESCRIPTION, ROW_VERSION, MAIN_CATEGORY_ABBREVIATION, OGRS_OFFENCE_CATEGORY_ID, SUB_CATEGORY_CODE, SUB_CATEGORY_DESCRIPTION, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME)
VALUES (2, '00102', 'Fraud - 00102', '001', 'Y', 'Fraud', 1, 'Fraud', 1, '02', 'Fraud', 1, '2017-01-01', 1, '2017-01-01');

INSERT INTO R_OFFENCE (OFFENCE_ID, CODE, DESCRIPTION, MAIN_CATEGORY_CODE, SELECTABLE, MAIN_CATEGORY_DESCRIPTION, ROW_VERSION, MAIN_CATEGORY_ABBREVIATION, OGRS_OFFENCE_CATEGORY_ID, SUB_CATEGORY_CODE, SUB_CATEGORY_DESCRIPTION, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME)
VALUES (3, '00103', 'Perjury - 00103', '001', 'Y', 'Perjury', 1, 'Perjury', 1, '03', 'Perjury', 1, '2017-01-01', 1, '2017-01-01');

INSERT INTO MAIN_OFFENCE (MAIN_OFFENCE_ID, OFFENCE_DATE, OFFENCE_COUNT, EVENT_ID, SOFT_DELETED, PARTITION_AREA_ID, OFFENCE_ID, OFFENDER_ID, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, TICS, VERDICT)
VALUES (1, '2018-06-05', 1, 1, 0, 1, 1, 1, 1, '2017-01-01', 1, '2017-01-01', 3, 'G');

INSERT INTO ADDITIONAL_OFFENCE (ADDITIONAL_OFFENCE_ID, OFFENCE_DATE, OFFENCE_COUNT, EVENT_ID, SOFT_DELETED, PARTITION_AREA_ID, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, OFFENCE_ID)
VALUES (1, '2017-01-01', 2, 1, 0, 1, 1, '2017-01-01', 1, '2017-01-01', 2);

INSERT INTO ADDITIONAL_OFFENCE (ADDITIONAL_OFFENCE_ID, OFFENCE_DATE, OFFENCE_COUNT, EVENT_ID, SOFT_DELETED, PARTITION_AREA_ID, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, OFFENCE_ID)
VALUES (2, '2017-01-01', 5, 1, 0, 1, 1, '2017-01-01', 1, '2017-01-01', 3);
