CREATE TABLE R_DISPOSAL_TYPE
(
  DISPOSAL_TYPE_ID NUMBER NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR2(128) NOT NULL,
);

CREATE TABLE DISPOSAL
(
	DISPOSAL_ID NUMBER NOT NULL PRIMARY KEY,
	EVENT_ID NUMBER NOT NULL,
	SOFT_DELETED NUMBER NOT NULL,
	OFFENDER_ID NUMBER NOT NULL,
	LENGTH NUMBER,
	EFFECTIVE_LENGTH NUMBER,
	LENGTH_IN_DAYS NUMBER,
	ENTRY_LENGTH NUMBER,
	LENGTH_2 NUMBER,
	ENTRY_LENGTH_UNITS_ID NUMBER,
	ENTRY_LENGTH_2_UNITS_ID NUMBER,
	DISPOSAL_TYPE_ID NUMBER NOT NULL
);

CREATE TABLE CUSTODY
(
	CUSTODY_ID NUMBER NOT NULL PRIMARY KEY,
	DISPOSAL_ID NUMBER NOT NULL,
	SOFT_DELETED NUMBER NOT NULL,
	OFFENDER_ID NUMBER NOT NULL
);

CREATE TABLE INSTITUTIONAL_REPORT
(
	INSTITUTIONAL_REPORT_ID NUMBER NOT NULL	PRIMARY KEY,
	CUSTODY_ID NUMBER NOT NULL,
	SOFT_DELETED NUMBER NOT NULL,
	OFFENDER_ID NUMBER NOT NULL
);