
INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4096, 'A', 'Tier A', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);

INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4097, 'B1', 'Tier B1', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);

INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4098, 'B2', 'Tier B2', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);

INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4099, 'C1', 'Tier C1', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);

INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4100, 'D1', 'Tier D1', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);

INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4101, 'D2', 'Tier D2', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);

INSERT INTO R_STANDARD_REFERENCE_LIST (STANDARD_REFERENCE_LIST_ID, CODE_VALUE, CODE_DESCRIPTION, SELECTABLE, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, REFERENCE_DATA_MASTER_ID, ROW_VERSION)
VALUES (4102, 'NA', 'Not Yet Assessed', 'Y', 1, '2018-01-01', 1, '2018-01-01', 1, 1);
