-- There is seed data for two test scenarios related to INACTIVE and SOFT_DELETED rows

--
-- TEST 1: Officer SH0001 already has three offenders assigned (previous seed data) and is the offender manager and responsible officer for all.
--         Insert a fourth offender into this relationship (G3131VA) but make the row SOFT_DELETED=1
--         This offender should not show up in the test results when calling getManagedOffenders for officer SH0001
--

-- Seed an OFFENDER who has been soft deleted but still in a relationship with an OFFENDER_MANAGER (staff officer SH0006) and a RESPONSIBLE_OFFICER (both expired)
INSERT INTO OFFENDER (OFFENDER_ID, FIRST_NAME, CRN, SECOND_NAME, PNC_NUMBER, CRO_NUMBER, SURNAME, FIRST_NAME_SOUNDEX, SURNAME_SOUNDEX, NOMS_NUMBER, ALLOW_SMS, DATE_OF_BIRTH_DATE,NI_NUMBER,
                      PARTITION_AREA_ID, SOFT_DELETED, ROW_VERSION, TITLE_ID, GENDER_ID, ETHNICITY_ID, NATIONALITY_ID, IMMIGRATION_STATUS_ID, LANGUAGE_ID, RELIGION_ID,
                      SECOND_NATIONALITY_ID, CREATED_DATETIME, MOST_RECENT_PRISONER_NUMBER, LAST_UPDATED_DATETIME, SEXUAL_ORIENTATION_ID, CURRENT_EXCLUSION,
                      CREATED_BY_USER_ID, LAST_UPDATED_USER_ID, TRAINING_SESSION_ID, LAST_UPDATED_USER_ID_DIVERSITY, CURRENT_DISPOSAL, CURRENT_HIGHEST_RISK_COLOUR, CURRENT_RESTRICTION,
                      INSTITUTION_ID, ESTABLISHMENT, CURRENT_TIER, PENDING_TRANSFER, CURRENT_REMAND_STATUS, OM_ALLOCATION_DECISION_ID,
                      PREV_CON_LAST_UPD_AUTH_PROV_ID, TRANSGENDER_PROCESS_ID, TRANSGENDER_CONSENT_DISCLOSE, MENTAL_HEALTH, SAFEGUARDING_ISSUE,
                      DISABILITY, IOM_NOMINAL, VULNERABILITY_ISSUE, INTERPRETER_REQUIRED)
VALUES (31,'DAVID', 'CRN31', '', 'PNC31', 'CRO31', 'SOFT-DELETED', ' ', ' ', 'G3131VA', 'Y', to_date('08-NOV-97','DD-MON-RR'), 'AB313131', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, to_date('12-DEC-18','DD-MON-RR'), 'G3131VA',
        to_date('12-DEC-18','DD-MON-RR'), 1, 0, 1, 1, 1, 1, 0, 'RED', 0, 1, 'Y', 1, 0, 'CONVICTED',1,12,1,'N','N','N','N','N','N','N');


-- Seed an OFFENDER_MANAGER row linking the above soft-deleted offender to officer code SH0001, but inactive and soft deleted
INSERT INTO OFFENDER_MANAGER (OFFENDER_MANAGER_ID, ALLOCATION_DATE, END_DATE, ALLOCATION_STAFF_ID, TEAM_ID, PARTITION_AREA_ID,OFFENDER_ID,
                              SOFT_DELETED,ROW_VERSION,ALLOCATION_REASON_ID,PROVIDER_EMPLOYEE_ID, OFFENDER_TRANSFER_ID, PROVIDER_TEAM_ID,
                              TRAINING_SESSION_ID, TRUST_PROVIDER_FLAG,STAFF_EMPLOYEE_ID,PROBATION_AREA_ID,TRUST_PROVIDER_TEAM_ID,ACTIVE_FLAG,
                              CREATED_BY_USER_ID, CREATED_DATETIME,LAST_UPDATED_USER_ID,LAST_UPDATED_DATETIME)
VALUES (26, to_date('08-MAY-18','DD-MON-RR'), to_date('08-FEB-19','DD-MON-RR') , 11, 11, 1, 31, 1, 1, 1, null, null, null, 1, 0, 11, 11, 1, 0, 1, to_date('12-DEC-18','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'));

-- Seed an expired (past its end date) RESPONSIBLE_OFFICER row with links to the soft-deleted OFFENDER and OFFENDER_MANAGER above
INSERT INTO RESPONSIBLE_OFFICER (RESPONSIBLE_OFFICER_ID, OFFENDER_ID, OFFENDER_MANAGER_ID, PRISON_OFFENDER_MANAGER_ID, START_DATE, END_DATE,
                                 CREATED_BY_USER_ID,CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, ROW_VERSION)
VALUES (17, 31, 26, null, to_date('12-DEC-18','DD-MON-RR'), to_date('12-FEB-19','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'), 1);

--
-- TEST 2: Create new STAFF and OFFICER rows for officer code SH0008
--         Add two new and valid OFFENDER rows
--         Create two OFFENDER_MANAGER rows for these offenders, linked to the officer - but one of these OFFENDER_MANAGERs is SOFT_DELETED
--         Create two valid RESPONSIBLE_OFFICER rows for the offenders and offender managers above.
--         When calling the API for getManagedOffenders for SH0008 only one offender should be returned (ignoring the other with a SOFT_DELETED offender manager)
--


-- Seed a valid staff row
INSERT INTO STAFF (STAFF_ID, START_DATE, SURNAME, END_DATE, FORENAME, ROW_VERSION, FORENAME2, STAFF_GRADE_ID, TITLE_ID, OFFICER_CODE, CREATED_BY_USER_ID,
                   LAST_UPDATED_USER_ID, CREATED_DATETIME, LAST_UPDATED_DATETIME, TRAINING_SESSION_ID, PRIVATE, SC_PROVIDER_ID, PROBATION_AREA_ID)
VALUES (18,to_date('01-JAN-18','DD-MON-RR'),'ONE-OFFENDER',null,'OLIVER',1,'',1,1,'SH0008',1,1,to_date('01-JAN-18','DD-MON-RR'),to_date('01-JAN-18','DD-MON-RR'),null,0,12,12);

-- Seed a valid officer
INSERT INTO OFFICER (TRUST_PROVIDER_FLAG, STAFF_EMPLOYEE_ID, SURNAME, FORENAME, FORENAME2, ROW_VERSION, TRAINING_SESSION_ID, STAFF_GRADE_ID, START_DATE, END_DATE)
VALUES (0, 18, 'ONE-OFFENDER', 'OLIVER', '', 1, 1, 1, to_date('08-NOV-11','DD-MON-RR'), to_date('08-NOV-30','DD-MON-RR'));

-- Seed a valid offender
INSERT INTO OFFENDER (OFFENDER_ID, FIRST_NAME, CRN, SECOND_NAME, PNC_NUMBER, CRO_NUMBER, SURNAME, FIRST_NAME_SOUNDEX, SURNAME_SOUNDEX, NOMS_NUMBER, ALLOW_SMS, DATE_OF_BIRTH_DATE,NI_NUMBER,
                      PARTITION_AREA_ID, SOFT_DELETED, ROW_VERSION, TITLE_ID, GENDER_ID, ETHNICITY_ID, NATIONALITY_ID, IMMIGRATION_STATUS_ID, LANGUAGE_ID, RELIGION_ID,
                      SECOND_NATIONALITY_ID, CREATED_DATETIME, MOST_RECENT_PRISONER_NUMBER, LAST_UPDATED_DATETIME, SEXUAL_ORIENTATION_ID, CURRENT_EXCLUSION,
                      CREATED_BY_USER_ID, LAST_UPDATED_USER_ID, TRAINING_SESSION_ID, LAST_UPDATED_USER_ID_DIVERSITY, CURRENT_DISPOSAL, CURRENT_HIGHEST_RISK_COLOUR, CURRENT_RESTRICTION,
                      INSTITUTION_ID, ESTABLISHMENT, CURRENT_TIER, PENDING_TRANSFER, CURRENT_REMAND_STATUS, OM_ALLOCATION_DECISION_ID,
                      PREV_CON_LAST_UPD_AUTH_PROV_ID, TRANSGENDER_PROCESS_ID, TRANSGENDER_CONSENT_DISCLOSE, MENTAL_HEALTH, SAFEGUARDING_ISSUE,
                      DISABILITY, IOM_NOMINAL, VULNERABILITY_ISSUE, INTERPRETER_REQUIRED)
VALUES (32, 'VICTOR', 'CRN32', '', 'PNC32', 'CRO32', 'VALID', ' ', ' ', 'G3232VA', 'Y', to_date('08-NOV-97','DD-MON-RR'), 'AB323232', 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, to_date('12-DEC-18','DD-MON-RR'), 'G3232VA',
        to_date('12-DEC-18','DD-MON-RR'), 1, 0, 1, 1, 1, 1, 0, 'RED', 0, 1, 'Y', 1, 0, 'CONVICTED',1,12,1,'N','N','N','N','N','N','N');

-- Seed another offender - this one soft-deleted
INSERT INTO OFFENDER (OFFENDER_ID, FIRST_NAME, CRN, SECOND_NAME, PNC_NUMBER, CRO_NUMBER, SURNAME, FIRST_NAME_SOUNDEX, SURNAME_SOUNDEX, NOMS_NUMBER, ALLOW_SMS, DATE_OF_BIRTH_DATE,NI_NUMBER,
                      PARTITION_AREA_ID, SOFT_DELETED, ROW_VERSION, TITLE_ID, GENDER_ID, ETHNICITY_ID, NATIONALITY_ID, IMMIGRATION_STATUS_ID, LANGUAGE_ID, RELIGION_ID,
                      SECOND_NATIONALITY_ID, CREATED_DATETIME, MOST_RECENT_PRISONER_NUMBER, LAST_UPDATED_DATETIME, SEXUAL_ORIENTATION_ID, CURRENT_EXCLUSION,
                      CREATED_BY_USER_ID, LAST_UPDATED_USER_ID, TRAINING_SESSION_ID, LAST_UPDATED_USER_ID_DIVERSITY, CURRENT_DISPOSAL, CURRENT_HIGHEST_RISK_COLOUR, CURRENT_RESTRICTION,
                      INSTITUTION_ID, ESTABLISHMENT, CURRENT_TIER, PENDING_TRANSFER, CURRENT_REMAND_STATUS, OM_ALLOCATION_DECISION_ID,
                      PREV_CON_LAST_UPD_AUTH_PROV_ID, TRANSGENDER_PROCESS_ID, TRANSGENDER_CONSENT_DISCLOSE, MENTAL_HEALTH, SAFEGUARDING_ISSUE,
                      DISABILITY, IOM_NOMINAL, VULNERABILITY_ISSUE, INTERPRETER_REQUIRED)
VALUES (33, 'VITO', 'CRN33', '', 'PNC33', 'CRO33', 'VALID', ' ', ' ', 'G3333VA', 'Y', to_date('08-NOV-97','DD-MON-RR'), 'AB333333', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, to_date('12-DEC-18','DD-MON-RR'), 'G3333VA',
        to_date('12-DEC-18','DD-MON-RR'), 1, 0, 1, 1, 1, 1, 0, 'RED', 0, 1, 'Y', 1, 0, 'CONVICTED',1,12,1,'N','N','N','N','N','N','N');


-- Seed a valid OFFENDER_MANAGER for offender G3232VA
INSERT INTO OFFENDER_MANAGER (OFFENDER_MANAGER_ID, ALLOCATION_DATE, END_DATE, ALLOCATION_STAFF_ID, TEAM_ID, PARTITION_AREA_ID,OFFENDER_ID,
                              SOFT_DELETED,ROW_VERSION,ALLOCATION_REASON_ID,PROVIDER_EMPLOYEE_ID, OFFENDER_TRANSFER_ID, PROVIDER_TEAM_ID,
                              TRAINING_SESSION_ID, TRUST_PROVIDER_FLAG,STAFF_EMPLOYEE_ID,PROBATION_AREA_ID,TRUST_PROVIDER_TEAM_ID,ACTIVE_FLAG,
                              CREATED_BY_USER_ID, CREATED_DATETIME,LAST_UPDATED_USER_ID,LAST_UPDATED_DATETIME)
VALUES (27, to_date('08-MAY-18','DD-MON-RR'), null, 18, 12, 1, 32, 0, 1, 1, null, null, null, 1, 0, 18, 12, 1, 1, 1, to_date('12-DEC-18','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'));


-- Seed a SOFT_DELETED and inactive OFFENDER_MANAGER for offender G3333VA
INSERT INTO OFFENDER_MANAGER (OFFENDER_MANAGER_ID, ALLOCATION_DATE, END_DATE, ALLOCATION_STAFF_ID, TEAM_ID, PARTITION_AREA_ID,OFFENDER_ID,
                              SOFT_DELETED,ROW_VERSION,ALLOCATION_REASON_ID,PROVIDER_EMPLOYEE_ID, OFFENDER_TRANSFER_ID, PROVIDER_TEAM_ID,
                              TRAINING_SESSION_ID, TRUST_PROVIDER_FLAG,STAFF_EMPLOYEE_ID,PROBATION_AREA_ID,TRUST_PROVIDER_TEAM_ID,ACTIVE_FLAG,
                              CREATED_BY_USER_ID, CREATED_DATETIME,LAST_UPDATED_USER_ID,LAST_UPDATED_DATETIME)
VALUES (28, to_date('08-MAY-18','DD-MON-RR'), to_date('08-FEB-19','DD-MON-RR'), 18, 12, 1, 33, 1, 1, 1, null, null, null, 1, 0, 18, 12, 1, 0, 1, to_date('12-DEC-18','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'));

-- Seed a valid RESPONSIBLE_OFFICER for valid OFFENDER G3232VA
INSERT INTO RESPONSIBLE_OFFICER (RESPONSIBLE_OFFICER_ID, OFFENDER_ID, OFFENDER_MANAGER_ID, PRISON_OFFENDER_MANAGER_ID, START_DATE, END_DATE,
                                 CREATED_BY_USER_ID,CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, ROW_VERSION)
VALUES (18, 32, 27, null, to_date('12-DEC-18','DD-MON-RR'), null, 1, to_date('12-DEC-18','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'), 1);

-- Seed an expired RESPONSIBLE_OFFICER for deleted OFFENDER G333VA
INSERT INTO RESPONSIBLE_OFFICER (RESPONSIBLE_OFFICER_ID, OFFENDER_ID, OFFENDER_MANAGER_ID, PRISON_OFFENDER_MANAGER_ID, START_DATE, END_DATE,
                                 CREATED_BY_USER_ID,CREATED_DATETIME, LAST_UPDATED_USER_ID, LAST_UPDATED_DATETIME, ROW_VERSION)
VALUES (19, 33, 28, null, to_date('12-DEC-18','DD-MON-RR'), to_date('12-FEB-19','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'), 1, to_date('12-DEC-18','DD-MON-RR'), 1);
