CREATE TABLE EXCLUSION
(
  EXCLUSION_ID             NUMBER           NOT NULL
    PRIMARY KEY,
  OFFENDER_ID              NUMBER           NOT NULL
    REFERENCES OFFENDER,
  USER_ID                  NUMBER           NOT NULL,
  EXCLUSION_DATE           DATE             NOT NULL,
  EXCLUSION_END_DATE       DATE,
  EXCLUSION_END_TIME       DATE,
  EXCLUSION_START_STAFF_ID NUMBER           NOT NULL,
  ROW_VERSION              NUMBER DEFAULT 0 NOT NULL,
  EXCLUSION_REASON_ID      NUMBER           NOT NULL
    REFERENCES R_STANDARD_REFERENCE_LIST,
  EXCLUSION_END_STAFF_ID   NUMBER,
  CREATED_DATETIME         DATE             NOT NULL,
  LAST_UPDATED_DATETIME    DATE             NOT NULL,
  PARTITION_AREA_ID        NUMBER           NOT NULL,
  EXCLUSION_START_TEAM_ID  NUMBER           NOT NULL,
  CREATED_BY_USER_ID       NUMBER           NOT NULL,
  EXCLUSION_END_TEAM_ID    NUMBER,
  LAST_UPDATED_USER_ID     NUMBER           NOT NULL,
  TRAINING_SESSION_ID      NUMBER
);

CREATE TABLE RESTRICTION
(
  RESTRICTION_ID             NUMBER           NOT NULL
    PRIMARY KEY,
  OFFENDER_ID                NUMBER           NOT NULL
    REFERENCES OFFENDER,
  USER_ID                    NUMBER           NOT NULL,
  RESTRICTION_DATE           DATE             NOT NULL,
  RESTRICTION_TIME           DATE             NOT NULL,
  RESTRICTION_START_STAFF_ID NUMBER           NOT NULL,
  RESTRICTION_END_DATE       DATE,
  RESTRICTION_END_TIME       DATE,
  ROW_VERSION                NUMBER DEFAULT 0 NOT NULL,
  RESTRICTION_REASON_ID      NUMBER           NOT NULL
    REFERENCES R_STANDARD_REFERENCE_LIST,
  RESTRICTION_END_STAFF_ID   NUMBER,
  CREATED_DATETIME           DATE             NOT NULL,
  LAST_UPDATED_DATETIME      DATE             NOT NULL,
  PARTITION_AREA_ID          NUMBER           NOT NULL,
  RESTRICTION_START_TEAM_ID  NUMBER           NOT NULL,
  CREATED_BY_USER_ID         NUMBER           NOT NULL,
  RESTRICTION_END_TEAM_ID    NUMBER,
  LAST_UPDATED_USER_ID       NUMBER           NOT NULL,
  TRAINING_SESSION_ID        NUMBER
);



