CREATE TABLE OFFENDER_MANAGER
(
  OFFENDER_MANAGER_ID    NUMBER NOT NULL
    PRIMARY KEY,
  ALLOCATION_DATE        DATE   NOT NULL,
  END_DATE               DATE,
  TEAM_ID                NUMBER
    REFERENCES TEAM,
  ALLOCATION_STAFF_ID    NUMBER
    REFERENCES STAFF,
  PARTITION_AREA_ID      NUMBER NOT NULL
    REFERENCES PARTITION_AREA,
  OFFENDER_ID            NUMBER NOT NULL
    REFERENCES OFFENDER,
  SOFT_DELETED           NUMBER NOT NULL,
  ALLOCATION_REASON_ID   NUMBER NOT NULL
    REFERENCES R_STANDARD_REFERENCE_LIST,
  PROVIDER_EMPLOYEE_ID   NUMBER
    REFERENCES PROVIDER_EMPLOYEE,
  PROVIDER_TEAM_ID       NUMBER
    REFERENCES PROVIDER_TEAM,
  TRUST_PROVIDER_FLAG    NUMBER NOT NULL,
  STAFF_EMPLOYEE_ID      NUMBER NOT NULL,
  PROBATION_AREA_ID      NUMBER NOT NULL
    REFERENCES PROBATION_AREA,
  TRUST_PROVIDER_TEAM_ID NUMBER NOT NULL,
  ACTIVE_FLAG            NUMBER NOT NULL
);

CREATE TABLE BOROUGH
(
  BOROUGH_ID        NUMBER       NOT NULL
    PRIMARY KEY,
  CODE              VARCHAR2(20) NOT NULL,
  DESCRIPTION       VARCHAR2(30) NOT NULL,
  SELECTABLE        CHAR         NOT NULL,
  PROBATION_AREA_ID NUMBER       NOT NULL
    REFERENCES PROBATION_AREA
);

CREATE TABLE DISTRICT
(
  DISTRICT_ID NUMBER       NOT NULL
    PRIMARY KEY,
  CODE        VARCHAR2(20) NOT NULL,
  DESCRIPTION VARCHAR2(30) NOT NULL,
  SELECTABLE  CHAR         NOT NULL,
  BOROUGH_ID  NUMBER       NOT NULL
    REFERENCES BOROUGH
);

CREATE TABLE ALL_TEAM
(
  TRUST_PROVIDER_FLAG    NUMBER NOT NULL,
  TRUST_PROVIDER_TEAM_ID NUMBER NOT NULL,
  PROBATION_AREA_ID      NUMBER
    REFERENCES PROBATION_AREA,
  DESCRIPTION            VARCHAR2(500),
  TELEPHONE              VARCHAR2(35),
  DISTRICT_ID            NUMBER
    REFERENCES DISTRICT,
  START_DATE             DATE   NOT NULL,
  END_DATE               DATE   NOT NULL
);