CREATE TABLE USER_
(
  USER_ID                        NUMBER           NOT NULL
    CONSTRAINT XPKUSER_
    PRIMARY KEY,
  STAFF_ID                       NUMBER
    REFERENCES STAFF,
  PROVIDER_EMPLOYEE_ID           NUMBER
    REFERENCES PROVIDER_EMPLOYEE,
  SURNAME                        VARCHAR2(35)     NOT NULL,
  FORENAME                       VARCHAR2(35)     NOT NULL,
  FORENAME2                      VARCHAR2(35),
  END_DATE                       DATE,
  NOTES                          CLOB,
  ROW_VERSION                    NUMBER DEFAULT 0 NOT NULL,
  DISTINGUISHED_NAME             VARCHAR2(500)    NOT NULL,
  EXTERNAL_PROVIDER_EMPLOYEEFLAG CHAR
    CONSTRAINT YES_OR_NO_435
    CHECK (EXTERNAL_PROVIDER_EMPLOYEEFLAG IN ('Y', 'N')),
  EXTERNAL_PROVIDER_ID           NUMBER,
  PRIVATE                        NUMBER           NOT NULL
    CONSTRAINT TRUE_OR_FALSE_941631159
    CHECK (PRIVATE IN (0, 1)),
  ORGANISATION_ID                NUMBER           NOT NULL,
  SC_PROVIDER_ID                 NUMBER,
  CONSTRAINT XAK1USER_
  UNIQUE (USER_ID, DISTINGUISHED_NAME)
);

CREATE TABLE PROBATION_AREA_USER
(
  USER_ID               NUMBER           NOT NULL
    REFERENCES USER_,
  PROBATION_AREA_ID     NUMBER           NOT NULL
    REFERENCES PROBATION_AREA,
  ROW_VERSION           NUMBER DEFAULT 0 NOT NULL,
  CREATED_DATETIME      DATE             NOT NULL,
  CREATED_BY_USER_ID    NUMBER           NOT NULL,
  LAST_UPDATED_DATETIME DATE             NOT NULL,
  LAST_UPDATED_USER_ID  NUMBER           NOT NULL,
  TRAINING_SESSION_ID   NUMBER,
  CONSTRAINT XPKPROBATION_AREA_USER
  PRIMARY KEY (USER_ID, PROBATION_AREA_ID)
);
