CREATE TABLE ADDRESS
(
  ADDRESS_ID            NUMBER           NOT NULL
    CONSTRAINT XPKADDRESS
    PRIMARY KEY,
  BUILDING_NAME         VARCHAR2(35),
  ADDRESS_NUMBER        VARCHAR2(35),
  STREET_NAME           VARCHAR2(35),
  DISTRICT              VARCHAR2(35),
  TOWN_CITY             VARCHAR2(35),
  POSTCODE              VARCHAR2(8),
  COUNTY                VARCHAR2(35),
  SOFT_DELETED          NUMBER           NOT NULL
    CONSTRAINT TRUE_OR_FALSE39
    CHECK (SOFT_DELETED IN (0, 1)),
  TELEPHONE_NUMBER      VARCHAR2(35),
  PARTITION_AREA_ID     NUMBER           NOT NULL
    REFERENCES PARTITION_AREA,
  ROW_VERSION           NUMBER DEFAULT 0 NOT NULL,
  CREATED_BY_USER_ID    NUMBER           NOT NULL,
  CREATED_DATETIME      DATE             NOT NULL,
  LAST_UPDATED_USER_ID  NUMBER           NOT NULL,
  LAST_UPDATED_DATETIME DATE             NOT NULL
);

CREATE TABLE ORGANISATION
(
  ORGANISATION_ID       NUMBER           NOT NULL
    CONSTRAINT XPKORGANISATION
    PRIMARY KEY,
  CODE                  VARCHAR2(20)     NOT NULL,
  DESCRIPTION           VARCHAR2(200)    NOT NULL,
  CONTACT_NAME          VARCHAR2(200),
  ADDRESS_ID            NUMBER           NOT NULL
    CONSTRAINT R_886
    REFERENCES ADDRESS,
  PRIVATE               NUMBER           NOT NULL
    CONSTRAINT TRUE_OR_FALSE_1719627878
    CHECK (PRIVATE IN (0, 1)),
  START_DATE            DATE             NOT NULL,
  END_DATE              DATE,
  ACTIVE_FLAG           NUMBER           NOT NULL,
  ROW_VERSION           NUMBER DEFAULT 0 NOT NULL,
  CREATED_BY_USER_ID    NUMBER           NOT NULL,
  CREATED_DATETIME      DATE             NOT NULL,
  LAST_UPDATED_USER_ID  NUMBER           NOT NULL,
  LAST_UPDATED_DATETIME DATE             NOT NULL
);