CREATE TABLE COURT
(
	COURT_ID NUMBER NOT NULL
		CONSTRAINT XPKCOURT
			PRIMARY KEY,
	CODE CHAR(6) NOT NULL,
	SELECTABLE CHAR NOT NULL
		CONSTRAINT YES_OR_NO
			CHECK (SELECTABLE IN ('N','Y')),
	COURT_NAME VARCHAR2(80),
	TELEPHONE_NUMBER VARCHAR2(35),
	FAX VARCHAR2(35),
	BUILDING_NAME VARCHAR2(35),
	STREET VARCHAR2(35),
	LOCALITY VARCHAR2(35),
	TOWN VARCHAR2(35),
	COUNTY VARCHAR2(35),
	POSTCODE VARCHAR2(8),
	COUNTRY VARCHAR2(16),
	ROW_VERSION NUMBER DEFAULT 0 NOT NULL,
	COURT_TYPE_ID NUMBER NOT NULL
		REFERENCES R_STANDARD_REFERENCE_LIST,
	CREATED_DATETIME DATE NOT NULL,
	CREATED_BY_USER_ID NUMBER NOT NULL,
	LAST_UPDATED_DATETIME DATE NOT NULL,
	LAST_UPDATED_USER_ID NUMBER NOT NULL,
	TRAINING_SESSION_ID NUMBER,
	PROBATION_AREA_ID NUMBER NOT NULL
		REFERENCES PROBATION_AREA,
	SECURE_EMAIL_ADDRESS VARCHAR2(255),
	CONSTRAINT XAK1COURT
		UNIQUE (CODE, TRAINING_SESSION_ID, COURT_ID)
);

CREATE TABLE COURT_APPEARANCE
(
	COURT_APPEARANCE_ID NUMBER NOT NULL
		CONSTRAINT XPKCOURT_APPEARANCE
			PRIMARY KEY,
	APPEARANCE_DATE DATE NOT NULL,
	CROWN_COURT_CALENDAR_NUMBER VARCHAR2(20),
	BAIL_CONDITIONS VARCHAR2(256),
	COURT_NOTES CLOB,
	EVENT_ID NUMBER NOT NULL
		REFERENCES EVENT,
	TEAM_ID NUMBER
		REFERENCES TEAM,
	STAFF_ID NUMBER
		REFERENCES STAFF,
	SOFT_DELETED NUMBER NOT NULL
		CONSTRAINT TRUE_OR_FALSE26
			CHECK (SOFT_DELETED IN (0, 1)),
	PARTITION_AREA_ID NUMBER NOT NULL
		REFERENCES PARTITION_AREA,
	COURT_ID NUMBER NOT NULL
		REFERENCES COURT,
	ROW_VERSION NUMBER DEFAULT 0 NOT NULL,
	APPEARANCE_TYPE_ID NUMBER NOT NULL
		REFERENCES R_STANDARD_REFERENCE_LIST,
	PLEA_ID NUMBER
		REFERENCES R_STANDARD_REFERENCE_LIST,
	OUTCOME_ID NUMBER
		REFERENCES R_STANDARD_REFERENCE_LIST,
	REMAND_STATUS_ID NUMBER
		REFERENCES R_STANDARD_REFERENCE_LIST,
	CREATED_BY_USER_ID NUMBER NOT NULL,
	CREATED_DATETIME DATE NOT NULL,
	LAST_UPDATED_USER_ID NUMBER NOT NULL,
	LAST_UPDATED_DATETIME DATE NOT NULL,
	TRAINING_SESSION_ID NUMBER,
	OFFENDER_ID NUMBER NOT NULL
		REFERENCES OFFENDER,
	ORGANISATIONS T_ARR_ORGANISATIONS
);

create table R_COURT_REPORT_TYPE
(
	COURT_REPORT_TYPE_ID NUMBER not null
		constraint XPKR_COURT_REPORT_TYPE
			primary key,
	CODE VARCHAR2(20) not null,
	DESCRIPTION VARCHAR2(50) not null,
	SELECTABLE CHAR not null
		constraint YES_OR_NO1
			check (SELECTABLE IN ('N','Y')),
	DELIVERED CHAR
		constraint YES_OR_NO_ONLY17
			check (DELIVERED IN ('Y','N')),
	ROW_VERSION NUMBER default 0 not null,
	REQUESTED CHAR
		constraint YES_OR_NO_ONLY18
			check (REQUESTED IN ('Y','N')),
	FORM_30_CODE VARCHAR2(20),
	PSR CHAR
		constraint YES_OR_NO_ONLY19
			check (PSR IN ('Y','N')),
	CREATED_BY_USER_ID NUMBER not null,
	CREATED_DATETIME DATE not null,
	LAST_UPDATED_USER_ID NUMBER not null,
	LAST_UPDATED_DATETIME DATE not null,
	TRAINING_SESSION_ID NUMBER,
	PRIVATE_TRANSFER CHAR not null
		constraint YES_OR_NO_ONLY_1294020556
			check (PRIVATE_TRANSFER IN ('Y','N')),
	constraint XAK1R_COURT_REPORT_TYPE
		unique (CODE, TRAINING_SESSION_ID, COURT_REPORT_TYPE_ID),
	constraint XAK2R_COURT_REPORT_TYPE
		unique (FORM_30_CODE, TRAINING_SESSION_ID, COURT_REPORT_TYPE_ID)
);

CREATE TABLE COURT_REPORT
(
	COURT_REPORT_ID NUMBER NOT NULL
		CONSTRAINT XPKCOURT_REPORT
			PRIMARY KEY,
	COURT_APPEARANCE_ID NUMBER NOT NULL
		REFERENCES COURT_APPEARANCE,
	DATE_REQUESTED DATE NOT NULL,
	DATE_REQUIRED DATE NOT NULL,
	ALLOCATION_DATE DATE,
	COMPLETED_DATE DATE,
	SENT_TO_COURT_DATE DATE,
	RECEIVED_BY_COURT_DATE DATE,
	VIDEO_LINK VARCHAR2(20),
	NOTES CLOB,
	PUNISHMENT CHAR
		CONSTRAINT YES_OR_NO_ONLY11
		CHECK (PUNISHMENT IN ('Y','N')),
	REDUCTION_OF_CRIME CHAR
		CONSTRAINT YES_OR_NO_ONLY12
		CHECK (REDUCTION_OF_CRIME IN ('Y','N')),
	REFORM_AND_REHABILITATION CHAR
		CONSTRAINT YES_OR_NO_ONLY13
		CHECK (REFORM_AND_REHABILITATION IN ('Y','N')),
	PUBLIC_PROTECTION CHAR
		CONSTRAINT YES_OR_NO_ONLY14
		CHECK (PUBLIC_PROTECTION IN ('Y','N')),
	REPARATION CHAR
		CONSTRAINT YES_OR_NO_ONLY15
		CHECK (REPARATION IN ('Y','N')),
	RECOMMENDATIONS_NOT_STATED CHAR
		CONSTRAINT YES_OR_NO_ONLY16
		CHECK (RECOMMENDATIONS_NOT_STATED IN ('Y','N')),
	SOFT_DELETED NUMBER NOT NULL
		CONSTRAINT TRUE_OR_FALSE27
		CHECK (SOFT_DELETED IN (0, 1)),
	PARTITION_AREA_ID NUMBER NOT NULL
		REFERENCES PARTITION_AREA,
	ROW_VERSION NUMBER DEFAULT 0 NOT NULL,
	LEVEL_OF_SERIOUSNESS_ID NUMBER NOT NULL
		REFERENCES R_STANDARD_REFERENCE_LIST,
	DELIVERED_REPORT_REASON_ID NUMBER
		REFERENCES R_STANDARD_REFERENCE_LIST,
	SECTION_178 CHAR
		CONSTRAINT YES_OR_NO_405
		CHECK (SECTION_178 IN ('Y','N')),
	CREATED_DATETIME DATE NOT NULL,
	LAST_UPDATED_DATETIME DATE NOT NULL,
	COURT_REPORT_TYPE_ID NUMBER
		REFERENCES R_COURT_REPORT_TYPE,
	CREATED_BY_USER_ID NUMBER NOT NULL,
	DELIVERED_COURT_REPORT_TYPE_ID NUMBER
		REFERENCES R_COURT_REPORT_TYPE,
	LAST_UPDATED_USER_ID NUMBER NOT NULL,
	TRAINING_SESSION_ID NUMBER,
	OFFENDER_ID NUMBER NOT NULL
		REFERENCES OFFENDER,
	ORGANISATIONS T_ARR_ORGANISATIONS,
	REQUIRED_BY_COURT_ID NUMBER
		CONSTRAINT R_787
		REFERENCES COURT,
	PENDING_TRANSFER NUMBER NOT NULL
		CONSTRAINT TRUE_OR_FALSE_218769512
		CHECK (PENDING_TRANSFER IN (0, 1))
);