name: Scan image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC

jobs:
  trivy:
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@8764f1a96d9a11b0e251308595d54132943d2c2e # v1
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}