name: Scan image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC

jobs:
  trivy:
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@e2737d6a74016918751829eae6fe832936c00c74 # v1
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}